filenames = [
"Inferno_*_Canto_I_speed_0.75.html",
"Inferno_*_Canto_II_speed_0.75.html",
"Inferno_*_Canto_III_speed_0.75.html",
"Inferno_*_Canto_IV_speed_0.75.html",
"Inferno_*_Canto_V_speed_0.75.html",
"Inferno_*_Canto_VI_speed_0.75.html",
"Inferno_*_Canto_VII_speed_0.75.html",
"Inferno_*_Canto_VIII_speed_0.75.html",
"Inferno_*_Canto_IX_speed_0.75.html",
"Inferno_*_Canto_X_speed_0.75.html",
"Inferno_*_Canto_XI_speed_0.75.html",
"Inferno_*_Canto_XII_speed_0.75.html",
"Inferno_*_Canto_XIII_speed_0.75.html",
"Inferno_*_Canto_XIV_speed_0.75.html",
"Inferno_*_Canto_XV_speed_0.75.html",
"Inferno_*_Canto_XVI_speed_0.75.html",
"Inferno_*_Canto_XVII_speed_0.75.html",
"Inferno_*_Canto_XVIII_speed_0.75.html",
"Inferno_*_Canto_XIX_speed_0.75.html",
"Inferno_*_Canto_XX_speed_0.75.html",
"Inferno_*_Canto_XXI_speed_0.75.html",
"Inferno_*_Canto_XXII_speed_0.75.html",
"Inferno_*_Canto_XXIII_speed_0.75.html",
"Inferno_*_Canto_XXIV_speed_0.75.html",
"Inferno_*_Canto_XXV_speed_0.75.html",
"Inferno_*_Canto_XXVI_speed_0.75.html",
"Inferno_*_Canto_XXVII_speed_0.75.html",
"Inferno_*_Canto_XXVIII_speed_0.75.html",
"Inferno_*_Canto_XXIX_speed_0.75.html",
"Inferno_*_Canto_XXX_speed_0.75.html",
"Inferno_*_Canto_XXXI_speed_0.75.html",
"Inferno_*_Canto_XXXII_speed_0.75.html",
"Inferno_*_Canto_XXXIII_speed_0.75.html",
"Inferno_*_Canto_XXXIV_speed_0.75.html",
"Purgatorio_*_Canto_I_speed_0.75.html",
"Purgatorio_*_Canto_II_speed_0.75.html",
"Purgatorio_*_Canto_III_speed_0.75.html",
"Purgatorio_*_Canto_IV_speed_0.75.html",
"Purgatorio_*_Canto_V_speed_0.75.html",
"Purgatorio_*_Canto_VI_speed_0.75.html",
"Purgatorio_*_Canto_VII_speed_0.75.html",
"Purgatorio_*_Canto_VIII_speed_0.75.html",
"Purgatorio_*_Canto_IX_speed_0.75.html",
"Purgatorio_*_Canto_X_speed_0.75.html",
"Purgatorio_*_Canto_XI_speed_0.75.html",
"Purgatorio_*_Canto_XII_speed_0.75.html",
"Purgatorio_*_Canto_XIII_speed_0.75.html",
"Purgatorio_*_Canto_XIV_speed_0.75.html",
"Purgatorio_*_Canto_XV_speed_0.75.html",
"Purgatorio_*_Canto_XVI_speed_0.75.html",
"Purgatorio_*_Canto_XVII_speed_0.75.html",
"Purgatorio_*_Canto_XVIII_speed_0.75.html",
"Purgatorio_*_Canto_XIX_speed_0.75.html",
"Purgatorio_*_Canto_XX_speed_0.75.html",
"Purgatorio_*_Canto_XXI_speed_0.75.html",
"Purgatorio_*_Canto_XXII_speed_0.75.html",
"Purgatorio_*_Canto_XXIII_speed_0.75.html",
"Purgatorio_*_Canto_XXIV_speed_0.75.html",
"Purgatorio_*_Canto_XXV_speed_0.75.html",
"Purgatorio_*_Canto_XXVI_speed_0.75.html",
"Purgatorio_*_Canto_XXVII_speed_0.75.html",
"Purgatorio_*_Canto_XXVIII_speed_0.75.html",
"Purgatorio_*_Canto_XXIX_speed_0.75.html",
"Purgatorio_*_Canto_XXX_speed_0.75.html",
"Purgatorio_*_Canto_XXXI_speed_0.75.html",
"Purgatorio_*_Canto_XXXII_speed_0.75.html",
"Purgatorio_*_Canto_XXXIII_speed_0.75.htm",
"Paradiso_*_Canto_I_speed_0.75.html",
"Paradiso_*_Canto_II_speed_0.75.html",
"Paradiso_*_Canto_III_speed_0.75.html",
"Paradiso_*_Canto_IV_speed_0.75.html",
"Paradiso_*_Canto_V_speed_0.75.html",
"Paradiso_*_Canto_VI_speed_0.75.html",
"Paradiso_*_Canto_VII_speed_0.75.html",
"Paradiso_*_Canto_VIII_speed_0.75.html",
"Paradiso_*_Canto_IX_speed_0.75.html",
"Paradiso_*_Canto_X_speed_0.75.html",
"Paradiso_*_Canto_XI_speed_0.75.html",
"Paradiso_*_Canto_XII_speed_0.75.html",
"Paradiso_*_Canto_XIII_speed_0.75.html",
"Paradiso_*_Canto_XIV_speed_0.75.html",
"Paradiso_*_Canto_XV_speed_0.75.html",
"Paradiso_*_Canto_XVI_speed_0.75.html",
"Paradiso_*_Canto_XVII_speed_0.75.html",
"Paradiso_*_Canto_XVIII_speed_0.75.html",
"Paradiso_*_Canto_XIX_speed_0.75.html",
"Paradiso_*_Canto_XX_speed_0.75.html",
"Paradiso_*_Canto_XXI_speed_0.75.html",
"Paradiso_*_Canto_XXII_speed_0.75.html",
"Paradiso_*_Canto_XXIII_speed_0.75.html",
"Paradiso_*_Canto_XXIV_speed_0.75.html",
"Paradiso_*_Canto_XXV_speed_0.75.html",
"Paradiso_*_Canto_XXVI_speed_0.75.html",
"Paradiso_*_Canto_XXVII_speed_0.75.html",
"Paradiso_*_Canto_XXVIII_speed_0.75.html",
"Paradiso_*_Canto_XXIX_speed_0.75.html",
"Paradiso_*_Canto_XXX_speed_0.75.html",
"Paradiso_*_Canto_XXXI_speed_0.75.html",
"Paradiso_*_Canto_XXXII_speed_0.75.html",
"Paradiso_*_Canto_XXXIII_speed_0.75.html"

]

def generate_html_grid(files):
    for f in files:
        # Extract parts for the display text
        parts = f.split('_')
        canticle = parts[0].upper()
        number = parts[3]
        
        print(f'<div class="item"><a href="{f}"><span class="canto-badge">{canticle} {number}</span> <span class="file-name">Canto {number}</span></a></div>')

generate_html_grid(filenames)
